### ISSUE TITLE
Nested Array

### ISSUE THREAD

**Issue by mpina83** [json-schema-form/angular-schema-form-bootstrap#9]
With the new version of the bootstrap decorator nested array dont work, the model stays unpopulated or populates de model with $$hashkey:object3243

i'm using a current schema like  object.Array[].Array[].field.

i've tried to include the "default" bootstrap decorator from the angularjs schema form and it's working has expected but the problem with the old is that the destroy strategy  isnt working properly in some situations.

**Comment by elbunuelo** [comment]
I believe you're having the same issue as I am. 
Here's the issue I created in the main Schema Form since the problem lays in the new array builder (https://github.com/Textalk/angular-schema-form/issues/590). In the issue I detailed a solution that (kind of) works and I'm waiting for an answer from the developers.

**Comment by mpina83** [comment]
Ty very much elbunuelo your fix solved part of my problems  xD still i got another nice one now:

https://github.com/OptimalBPM/angular-schema-form-dynamic-select/issues/63

apart from the radio buttons inside of a nested array arent working properly also

**Comment by Anthropic** [comment]
This should be fixed as per the merged issue.
